spring:
  application:
    name: discovery_cluster
eureka:
  client:
    ## eureka-server不需要注册自己也不需要拉取注册中心的数据
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  server:
    #关闭自我保护机制，及时剔除无效服务
    enable-self-preservation: false
---
spring:
  profiles: eureka1
server:
  port: 8761

eureka:
  instance:
    hostname: eureka1

---
spring:
  profiles: eureka2
server:
  port: 8762

eureka:
  instance:
    hostname: eureka2

---
spring:
  profiles: eureka3
server:
  port: 8763

eureka:
  instance:
    hostname: eureka3