eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
server:
  port: 6864
spring:
  application:
    name: service_feign
feign:
  hystrix:
    enabled: true