options:
  - order: 1
    desc: 连接聊天服务器
    handler: 123
  - order: 2
    desc: 展示所有在线人员
    handler: 123
  - order: 3
    desc: 发起聊天
    handler: 123
  - order: 4
    desc: 发起多人聊天
    handler: 123
  - order: 5
    desc: 退出
    handler: 123